# Site settings
title: Seba Menendez - Professional Surfer
email: sebisurfista@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/me/" # the subpath of your site, e.g. /blog/
url: "https://sebamenendez.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
